name: CI

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [20]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint
